site_name: Agenterprise - The AI Way to Model Driven Software Development
site_description: Documentation for Agenterprise, the AI way to model driven software development.
site_author: Michael Vonrüden
site_url: https://www.agenterprise.ai
repo_url: https://github.com/agenterprise/ai-layer-pydanticai


theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrated
    - content.code.annotate
    - content.code.copy
    - content.tabs.links
    - header.autohide
    - navigation.instant    
  static_templates:
    - 404.html
nav:
  - Home: index.md
  - AI DSL:
      - Overview: dsl/index.md 
      - Architecture Layer: dsl/architecture-layer.md
      - Infrastructure Layer: dsl/infrastruture-layer.md
      - AI Functional Layer: dsl/ai-functional-layer.md
      - Serivce Layer: dsl/service-layer.md

  - AI Generator: 
      - Overview: generator/index.md

  - Installation: installation.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agenterprise
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    provider: mike
copyright: >
  Copyright &copy; 2025  Michael Vonrüden –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - privacy
  - search